force-app/main/default/objects/Account/fields/DB_Block_Id__c.field-meta.xml
<CustomField>
    <fullName>DB_Block_Id__c</fullName>
    <label>D&amp;B Block Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DB_Block_Reason__c.field-meta.xml
<CustomField>
    <fullName>DB_Block_Reason__c</fullName>
    <label>D&amp;B Block Reason</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DB_Block_Status__c.field-meta.xml
<CustomField>
    <fullName>DB_Block_Status__c</fullName>
    <label>D&amp;B Block Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DB_Code__c.field-meta.xml
<CustomField>
    <fullName>DB_Code__c</fullName>
    <label>D&amp;B Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DB_Domestic_Ultimate_DUNS__c.field-meta.xml
<CustomField>
    <fullName>DB_Domestic_Ultimate_DUNS__c</fullName>
    <label>D&amp;B Domestic Ultimate DUNS</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DB_DUNS__c.field-meta.xml
<CustomField>
    <fullName>DB_DUNS__c</fullName>
    <externalId>true</externalId>
    <label>D&amp;B DUNS</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/DB_Global_Ultimate_DUNS__c.field-meta.xml
<CustomField>
    <fullName>DB_Global_Ultimate_DUNS__c</fullName>
    <label>D&amp;B Global Ultimate DUNS</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DB_Global_Ultimate_Name__c.field-meta.xml
<CustomField>
    <fullName>DB_Global_Ultimate_Name__c</fullName>
    <label>D&amp;B Global Ultimate Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DB_Incorporated_Date__c.field-meta.xml
<CustomField>
    <fullName>DB_Incorporated_Date__c</fullName>
    <label>D&amp;B Incorporated Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/DB_Industry__c.field-meta.xml
<CustomField>
    <fullName>DB_Industry__c</fullName>
    <label>D&amp;B Industry</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DB_Number_of_Employees__c.field-meta.xml
<CustomField>
    <fullName>DB_Number_of_Employees__c</fullName>
    <label>D&amp;B Number of Employees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DB_Number_of_Employees_Scope__c.field-meta.xml
<CustomField>
    <fullName>DB_Number_of_Employees_Scope__c</fullName>
    <label>D&amp;B Number of Employees Scope</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DB_Operating_Status__c.field-meta.xml
<CustomField>
    <fullName>DB_Operating_Status__c</fullName>
    <label>D&amp;B Operating Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DB_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>DB_Start_Date__c</fullName>
    <label>D&amp;B Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/DB_Telephone_Number__c.field-meta.xml
<CustomField>
    <fullName>DB_Telephone_Number__c</fullName>
    <label>D&amp;B Telephone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/DB_Website__c.field-meta.xml
<CustomField>
    <fullName>DB_Website__c</fullName>
    <label>D&amp;B Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/DB_Yearly_Revenue__c.field-meta.xml
<CustomField>
    <fullName>DB_Yearly_Revenue__c</fullName>
    <label>D&amp;B Yearly Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/DB_Yearly_Revenue_Currency__c.field-meta.xml
<CustomField>
    <fullName>DB_Yearly_Revenue_Currency__c</fullName>
    <label>D&amp;B Yearly Revenue Currency</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DunsResponseWrapper.cls
public class DunsResponseWrapper {
	// Internal
	public Account originating_Account;			// N/A
	public List<Account> account_Results;		// N/A
	public Boolean perform_Enrichment;			// N/A

	// Payload
	public ResponsePayload responsePayload;
	public class ResponsePayload {
        // Success
		public String status;
        public String message;
		public Integer count;
        public List<DunsResult> data;
		public String correlationId;

		// Failure
		public String reasonPhrase;
		public Integer statusCode; 
		public String errorMessage;
		public String errorDescription;
    }

	public class DunsResult {
		public CompanyDetail sitesDuns;
        public CompanyDetail domesticDuns;
        public CompanyDetail globalDuns;
    }

	public class CompanyDetail {
		public String duns;						// DB_DUNS__c
		public String description;				// DB_Industry__c
		public String globalUltimateDuns;		// DB_Global_Ultimate_DUNS__c
		public String domesticUltimateDuns;		// DB_Domestic_Ultimate_DUNS__c
		public String primaryName;				// DB_Global_Ultimate_Name__c
		public String blockID;					// DB_Block_Id__c
		public String blockStatus;				// DB_Block_Status__c
		public String blockStatusReason;		// DB_Block_Reason__c
		public String industryCodes;			// DB_Industry__c
		public String telephoneNumber;			// DB_Telephone_Number__c
		public String operatingStatus;			// DB_Operating_Status__c
		public String countryCode;				// DB_Address__CountryCode__s
		public String city;						// DB_Address__City__s
		public String stateCode;				// DB_Address__StateCode__s
		public String postalCode;				// DB_Address__PostalCode__s
		public String street;					// DB_Address__Street__s
		public String numberOfEmployeesScope;	// DB_Number_of_Employees_Scope__c
		public String yearlyRevenueCurrency;	// DB_Yearly_Revenue_Currency__c
		public String yearlyRevenue;			// DB_Yearly_Revenue__c
		public Date startDate;					// DB_Start_Date__c
		public Date incorporatedDate; 			// DB_Incorporated_Date__c
		public String fiscalYearEnd;
		public Integer dnbCode;					// DB_Code__c
		public Integer numberOfEmployees;		// DB_Number_of_Employees__c
		public WebsiteAddress websiteAddress;	// See subclass
		public Decimal latitude;
        public Decimal longitude;
	}
	
	public class WebsiteAddress {
		public String url;						// DB_Website__c
		public String domainName;
	}

	// Standard static method for easy deserialization
	public static DunsResponseWrapper parse(String jsonString) {
        return (DunsResponseWrapper) System.JSON.deserialize(jsonString, DunsResponseWrapper.class);
    }
}